"""Configuration: agent discovery (agents.py) + prompt generation (prompts.py).

The public API is re-exported here for backward compatibility — old imports
like `from src.config import discover_agents` keep working without touching
every call site.
"""

from .agents import (
    AGENTS_WITHOUT_FILE_SUPPORT,
    KNOWN_AGENTS,
    Agent,
    add_member_to_config,
    build_roster,
    check_agent_available,
    discover_agents,
    load_config,
    member_available,
    member_from_agent,
    member_from_config,
    save_config,
    select_members,
)
from .prompts import (
    ADVERSARIAL_SUFFIX,
    EVAL_SKILLS_INSTRUCTION,
    PRESET_EMPHASIS,
    REVIEW_CHANGELOG_MAX_CHARS,
    REVIEW_DRAFT_MAX_CHARS,
    REVIEW_OWN_R1_MAX,
    REVIEW_OWN_R2_MAX,
    SKILLS_INSTRUCTION,
    WORK_DISCUSSION_MAX,
    get_adversarial_suffix,
    get_evaluation_prompt,
    get_evidence_prompt_addition,
    get_fix_prompt,
    get_preset_emphasis,
    get_review_prompt,
    get_round2_prompt,
    get_round2_prompt_files,
    get_round3_prompt,
    get_round3_prompt_files,
    get_work_prompt,
)

__all__ = [
    "ADVERSARIAL_SUFFIX",
    "AGENTS_WITHOUT_FILE_SUPPORT",
    "EVAL_SKILLS_INSTRUCTION",
    "KNOWN_AGENTS",
    "PRESET_EMPHASIS",
    "REVIEW_CHANGELOG_MAX_CHARS",
    "REVIEW_DRAFT_MAX_CHARS",
    "REVIEW_OWN_R1_MAX",
    "REVIEW_OWN_R2_MAX",
    "SKILLS_INSTRUCTION",
    "WORK_DISCUSSION_MAX",
    "Agent",
    "add_member_to_config",
    "build_roster",
    "check_agent_available",
    "discover_agents",
    "get_adversarial_suffix",
    "get_evaluation_prompt",
    "get_evidence_prompt_addition",
    "get_fix_prompt",
    "get_preset_emphasis",
    "get_review_prompt",
    "get_round2_prompt",
    "get_round2_prompt_files",
    "get_round3_prompt",
    "get_round3_prompt_files",
    "get_work_prompt",
    "load_config",
    "member_available",
    "member_from_agent",
    "member_from_config",
    "save_config",
    "select_members",
]
